### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Dark-Arcana** [Frinn38/Ore-Factory#1]
I was looking to see if you had a Discord server for this modpack. It could be useful to add a discord server link to your modpack page on CurseForge.

**Comment by Frinn38** [comment]
Hello, we don't have a discord server now, for questions you can use curseforge comments or github (but I admit it is less convenient to use).
For now I don't see the point of a discord server just for this pack, but in the future, if the amount of questions/suggestions/requests increase we may need one.

**Comment by ghost** [comment]
I think a discord server would be good, I'll probably end up having a lot of questions myself and I know lots of people's first instinct is to check for a discord link rather than a github link when they're struggling and need help.
