### ISSUE TITLE
How do I get power?

### ISSUE THREAD

**Issue by ghost** [Frinn38/Ore-Factory#2]
The quest book tells me that I need a basic crusher, which i made. But the crusher requires power, and the quest book doesn't tell me how to get power.

**Comment by ghost** [comment]
Ok I figured out how to get power (I made two Starter Furnators from the powah mod) but now I have no idea how to get iron. The only way I can see is by using a blast furnace, but I need iron to make a hammer in order to create the blast furnace so I'm just stuck.

**Comment by Emalios** [comment]
We have published an update of the pack which fixes this problem by adding the recipes for age 1 ores in the vanilla furnace.
Sorry for the inconvenience, good game to you ^^
https://www.curseforge.com/minecraft/modpacks/ore-factory/files/3011905

**Comment by Frinn38** [comment]
There was a problem in some scripts, this is fixed in 0.3, so to make basic ingots (iron copper, tin and lead) you jush smelt the ore chunks you have with the crusher.
You already found out but you can make nearly all the starter tier of powah, I will see to show this more clearly in the quests.

**Comment by ghost** [comment]
I downloaded the new update from the twitch launcher and this recipe doesn't seem to be added.

**Comment by Frinn38** [comment]
Oh yes my bad the fix was not added in the update, I uploaded a 0.3.1 with the recipes fixed, you will be able to use it as soon as curseforge approve it.
