### ISSUE TITLE
Custom Ores Are Not Spawned or Added to JEI

### ISSUE THREAD

**Issue by steventopper** [Frinn38/Ore-Factory#5]
Pack Version: 0.4.0

Forge Version: 31.2.31

Issue: After creating a new world, the console prints out several lines saying that various ores do not appear to exist and that there was an issue running scripts (see img 1). After flying around the world for a bit, I saw no trace of any ore deposits underground and no ore markers on the surface. Finally, the ores (and chunks) are not searchable in JEI and are replaced with placeholders in the questbook (see img 2).

Steps to Recreate: Create a new default world.

IMG 1
![image](https://user-images.githubusercontent.com/6625247/88727070-e4f7c300-d0fc-11ea-94d1-5785cf028e52.png)

IMG 2
![image](https://user-images.githubusercontent.com/6625247/88727405-972f8a80-d0fd-11ea-95d0-03a1e68c4e34.png)

**Comment by ghost** [comment]
was literally just about to report this bug myself

**Comment by Frinn38** [comment]
There is some bugs in the version of KubeJS included in the pack 0.4 version.
For now you can just update KubeJS to it's latest version and it will works again.
I will push a lil update of the pack to correct this bug anyway.
